/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as TicketsCompanyIdTicketIdRouteImport } from './routes/tickets.$companyId.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsCompanyIdTicketIdRoute =
  TicketsCompanyIdTicketIdRouteImport.update({
    id: '/tickets/$companyId/$ticketId',
    path: '/tickets/$companyId/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/tickets/$companyId/$ticketId': typeof TicketsCompanyIdTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/tickets/$companyId/$ticketId': typeof TicketsCompanyIdTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/tickets/$companyId/$ticketId': typeof TicketsCompanyIdTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companies/$companyId' | '/tickets/$companyId/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies/$companyId' | '/tickets/$companyId/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/companies/$companyId'
    | '/tickets/$companyId/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  TicketsCompanyIdTicketIdRoute: typeof TicketsCompanyIdTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$companyId/$ticketId': {
      id: '/tickets/$companyId/$ticketId'
      path: '/tickets/$companyId/$ticketId'
      fullPath: '/tickets/$companyId/$ticketId'
      preLoaderRoute: typeof TicketsCompanyIdTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  TicketsCompanyIdTicketIdRoute: TicketsCompanyIdTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
